#!/usr/bin/env bash

nick="$1"
mesg="$2"
ircd="$3"
netw="$4"
chan="$5"
self="$6"
cdir="$7"

read -r cmd extra <<< "$mesg"
if [[ "$mesg" =~ .*\>.+ ]]; then
    read -r nicks <<< "${extra#*>}"
    read -r extra <<< "${extra%>*}"
fi

if [[ "$nicks" == "@all" ]]; then
    printf -- "/names %s\n" "$chan"
    nicks=""
    while test -z "$nicks"; do # wait for the response
        nicks="$(tail -n2 "$ircd/$netw/out" | grep "[[:digit:]-]\+ [[:digit:]:]\+ = $chan" | cut -d" " -f5-)"
        sleep .5
    done
fi

# Standard commands are defined below. Custom commands are loaded from $cdir
commands=(
    list
    $(find -L $cdir -type f -maxdepth 1 -mindepth 1 -printf '%f\n')
)

# Do not allow undefined commands
[[ "$commands" =~ $cmd ]] || exit

case "$cmd" in
    list)
        [[ -n "$nicks" ]] && printf -- "%s: %s\n" "$nicks" "${commands[*]}" || printf -- "%s: %s\n" "$nick" "${commands[*]}"
        ;;
    *)
        # Run external command
        [[ -e $cdir/$cmd ]] && source $cdir/$cmd
        ;;
esac
